import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import React from "react";
import { Pressable, ScrollView, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { Card, ScreenHeader, StatusPill } from "@/components/transport-ui";
import { useColors } from "@/hooks/use-colors";
import { useAppState } from "@/lib/app-state";
import { ROUTES, STOPS } from "@/lib/transport-data";

export default function AdminScreen() {
  const colors = useColors();
  const { buses } = useAppState();
  const metrics = [{ label: "Total buses", value: buses.length, icon: "directions-bus", color: colors.primary }, { label: "Active buses", value: buses.filter((bus) => bus.status !== "STOPPED").length, icon: "wifi-tethering", color: colors.success }, { label: "Delayed", value: buses.filter((bus) => bus.status === "DELAYED").length, icon: "warning", color: colors.warning }, { label: "Stopped", value: buses.filter((bus) => bus.status === "STOPPED").length, icon: "pause-circle", color: colors.muted }];
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 30 }}><ScreenHeader title="Admin console" subtitle="Demo operations dashboard" right={<StatusPill label="ADMIN" tone="warning" />} /><View className="flex-row flex-wrap justify-between gap-y-3">{metrics.map((metric) => <View key={metric.label} className="w-[48%] rounded-2xl bg-surface p-4"><MaterialIcons name={metric.icon as keyof typeof MaterialIcons.glyphMap} size={21} color={metric.color} /><Text className="mt-3 text-2xl font-black text-foreground">{metric.value}</Text><Text className="mt-1 text-xs text-muted">{metric.label}</Text></View>)}</View><Card className="mt-6"><Text className="mb-3 text-lg font-black text-foreground">Network health</Text><View className="flex-row items-center gap-3"><View style={{ backgroundColor: colors.successSoft }} className="h-10 w-10 items-center justify-center rounded-xl"><MaterialIcons name="check-circle" size={20} color={colors.success} /></View><View className="flex-1"><Text className="font-bold text-foreground">Demo realtime engine online</Text><Text className="mt-1 text-xs text-muted">Fleet positions refresh every 4 seconds.</Text></View><StatusPill label="HEALTHY" /></View></Card><View className="mt-6"><Text className="mb-3 text-xl font-black text-foreground">Management</Text><View className="gap-3"><AdminRow icon="directions-bus" title="Buses" subtitle={`${buses.length} registered vehicles`} onPress={() => router.push("/(tabs)/track")} /><AdminRow icon="route" title="Routes" subtitle={`${ROUTES.length} demo routes`} onPress={() => router.push("/(tabs)/routes")} /><AdminRow icon="location-on" title="Stops" subtitle={`${STOPS.length} mapped stops`} onPress={() => router.push("/(tabs)/nearby")} /><AdminRow icon="people" title="Drivers" subtitle="Demo driver accounts" onPress={() => router.push("/driver")} /><AdminRow icon="assessment" title="Reports" subtitle="Service performance summaries" onPress={() => undefined} /></View></View><Text className="mt-7 text-center text-xs leading-5 text-muted">Admin changes are local to this demo. Production data management will use authenticated backend APIs and database constraints.</Text></ScrollView></ScreenContainer>;
}
function AdminRow({ icon, title, subtitle, onPress }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; subtitle: string; onPress: () => void }) { const colors = useColors(); return <Pressable onPress={onPress} className="flex-row items-center rounded-2xl bg-surface px-4 py-3"><View style={{ backgroundColor: colors.surfaceAlt }} className="mr-3 h-10 w-10 items-center justify-center rounded-xl"><MaterialIcons name={icon} size={20} color={colors.primary} /></View><View className="flex-1"><Text className="font-black text-foreground">{title}</Text><Text className="mt-1 text-xs text-muted">{subtitle}</Text></View><MaterialIcons name="chevron-right" size={20} color={colors.muted} /></Pressable>; }
