import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import React from "react";
import { Pressable, ScrollView, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { Card, EmptyState, PrimaryButton, ScreenHeader, StatusPill } from "@/components/transport-ui";
import { useColors } from "@/hooks/use-colors";
import { useAppState } from "@/lib/app-state";

export default function AlertsScreen() {
  const colors = useColors();
  const { alerts, removeAlert } = useAppState();
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 30 }}><ScreenHeader title="Arrival alerts" subtitle="Never miss your bus" /><Card style={{ backgroundColor: colors.primary }}><View className="flex-row items-center gap-3"><View className="h-11 w-11 items-center justify-center rounded-xl bg-white/20"><MaterialIcons name="notifications-active" size={22} color="#FFFFFF" /></View><View className="flex-1"><Text className="text-base font-black text-white">Demo notifications enabled</Text><Text className="mt-1 text-xs leading-4 text-white/80">We’ll demonstrate an alert when a tracked bus is near your stop.</Text></View></View></Card><View className="mt-6"><View className="mb-3 flex-row items-center justify-between"><Text className="text-xl font-black text-foreground">Your alerts</Text><StatusPill label={`${alerts.length} active`} /></View>{alerts.length ? <View className="gap-3">{alerts.map((alert) => <Card key={alert.id}><View className="flex-row items-start"><MaterialIcons name="notifications" size={22} color={colors.primary} /><View className="ml-3 flex-1"><Text className="font-black text-foreground">{alert.busId} is {alert.threshold} min away</Text><Text className="mt-1 text-sm text-muted">Notify me near {alert.stopName}</Text><Text style={{ color: colors.success }} className="mt-2 text-xs font-bold">Demo alert ready</Text></View><Pressable onPress={() => removeAlert(alert.id)} className="p-1"><MaterialIcons name="close" size={19} color={colors.muted} /></Pressable></View></Card>)}</View> : <EmptyState icon="notifications-none" title="No alerts yet" message="Open any bus or stop and tap Set arrival alert." />}</View><View className="mt-6"><Text className="mb-3 text-xl font-black text-foreground">Notification preferences</Text><Card><Preference title="Bus approaching" enabled /><Preference title="Delay updates" enabled /><Preference title="Trip completed" enabled={false} /></Card></View><PrimaryButton title="Track a bus" icon="gps-fixed" onPress={() => router.push("/(tabs)/track")} style={{ marginTop: 20 }} /><Text className="mt-6 text-center text-xs leading-5 text-muted">Notifications are simulated locally in demo mode. Push delivery requires a connected backend.</Text></ScrollView></ScreenContainer>;
}
function Preference({ title, enabled }: { title: string; enabled: boolean }) { const colors = useColors(); return <View className="flex-row items-center border-b border-border py-3 last:border-0"><Text className="flex-1 font-bold text-foreground">{title}</Text><View style={{ backgroundColor: enabled ? colors.successSoft : colors.surfaceAlt }} className="rounded-full px-3 py-1"><Text style={{ color: enabled ? colors.success : colors.muted }} className="text-xs font-bold">{enabled ? "ON" : "OFF"}</Text></View></View>; }
