import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import React from "react";
import { Pressable, ScrollView, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

export default function RoleSelectScreen() {
  const colors = useColors();
  return <ScreenContainer className="px-5" edges={["top", "left", "right", "bottom"]}><ScrollView contentContainerStyle={{ flexGrow: 1, paddingBottom: 32 }} showsVerticalScrollIndicator={false}><View className="flex-1 justify-center pt-10"><View className="items-center"><View style={{ backgroundColor: colors.primary }} className="h-20 w-20 items-center justify-center rounded-[26px]"><MaterialIcons name="directions-bus" size={44} color="#FFFFFF" /></View><Text className="mt-6 text-center text-4xl font-black tracking-tight text-foreground">Find My Bus</Text><Text className="mt-2 max-w-[320px] text-center text-sm leading-5 text-muted">Real-time public bus tracking, GPS operations, and route management in one platform.</Text></View><View className="mt-10"><Text className="mb-3 text-xs font-black uppercase tracking-[1.5px] text-muted">Choose your workspace</Text><View className="gap-3"><RoleCard icon="person-pin" title="Passenger" description="Track buses, plan journeys, find stops, and view arrivals." tone="primary" onPress={() => router.replace("/(tabs)" as never)} /><RoleCard icon="drive-eta" title="Driver" description="Start a trip, share GPS location, and view live telemetry." tone="success" onPress={() => router.push("/driver")} /><RoleCard icon="admin-panel-settings" title="Administrator" description="Manage buses, routes, stops, drivers, and service data." tone="warning" locked onPress={() => router.push("/admin-lock" as never)} /></View></View><View style={{ backgroundColor: colors.surfaceAlt }} className="mt-8 rounded-2xl px-4 py-3"><View className="flex-row items-center gap-2"><MaterialIcons name="security" size={17} color={colors.primary} /><Text style={{ color: colors.primary }} className="flex-1 text-xs font-bold">Role-based access</Text></View><Text className="mt-1 text-[11px] leading-4 text-muted">Passenger tools are public. Driver and Admin workspaces are separate operational areas.</Text></View></View><Text className="mt-8 text-center text-[10px] text-muted">Find My Bus · Public transport operations platform</Text></ScrollView></ScreenContainer>;
}

function RoleCard({ icon, title, description, tone, locked, onPress }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; description: string; tone: "primary" | "success" | "warning"; locked?: boolean; onPress: () => void }) { const colors = useColors(); const palette = { primary: colors.primary, success: colors.success, warning: colors.warning }[tone]; return <Pressable onPress={onPress} style={({ pressed }) => [pressed && { opacity: 0.82, transform: [{ scale: 0.985 }] }]}><View className="flex-row items-center rounded-2xl border border-border bg-surface px-4 py-4"><View style={{ backgroundColor: tone === "primary" ? colors.primarySoft : tone === "success" ? colors.successSoft : colors.warningSoft }} className="mr-4 h-12 w-12 items-center justify-center rounded-xl"><MaterialIcons name={icon} size={24} color={palette} /></View><View className="flex-1"><View className="flex-row items-center gap-2"><Text className="text-base font-black text-foreground">{title}</Text>{locked ? <MaterialIcons name="lock" size={14} color={colors.warning} /> : null}</View><Text className="mt-1 text-xs leading-4 text-muted">{description}</Text></View><MaterialIcons name="chevron-right" size={22} color={colors.muted} /></View></Pressable>; }
