import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import React, { useMemo, useState } from "react";
import { Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { BusMap } from "@/components/bus-map";
import { Card, PrimaryButton, StatusPill } from "@/components/transport-ui";
import { useColors } from "@/hooks/use-colors";
import { useAppState } from "@/lib/app-state";
import { searchTransport } from "@/lib/transport-data";

export default function HomeScreen() {
  const colors = useColors();
  const { buses, isOffline, demoLocation } = useAppState();
  const [statusQuery, setStatusQuery] = useState("");
  const [from, setFrom] = useState("Kottara");
  const [to, setTo] = useState("Surathkal");
  const activeBuses = buses.filter((bus) => bus.status !== "STOPPED");
  const searchHint = useMemo(() => searchTransport(statusQuery), [statusQuery]);
  const handleStatusSearch = () => {
    if (!statusQuery.trim()) return;
    const match = searchHint.buses[0];
    if (match) router.push(`/bus/${match.id}`);
    else router.push(`/search?q=${encodeURIComponent(statusQuery)}`);
  };
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}>
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 34 }}>
      <View className="flex-row items-center justify-between pt-2">
        <View className="flex-row items-center gap-3"><View style={{ backgroundColor: colors.primary }} className="h-11 w-11 items-center justify-center rounded-2xl"><MaterialIcons name="directions-bus" size={25} color="#FFFFFF" /></View><View><Text className="text-xl font-black tracking-tight text-foreground">Find My Bus</Text><Text className="text-xs font-semibold text-muted">Your city. Your route. Your time.</Text></View></View>
        <Pressable onPress={() => router.push("/(tabs)/more")} className="h-10 w-10 items-center justify-center rounded-full bg-surface"><MaterialIcons name="more-horiz" size={23} color={colors.primary} /></Pressable>
      </View>
      <View className="mt-5 flex-row items-center gap-2"><MaterialIcons name="near-me" size={17} color={colors.primary} /><Text className="text-sm font-bold text-foreground">Mangaluru</Text><Text className="text-sm text-muted">• live network</Text><View className="flex-1" /><View className="flex-row items-center gap-1"><View style={{ backgroundColor: isOffline ? colors.warning : colors.success }} className="h-2 w-2 rounded-full" /><Text className="text-[11px] font-bold text-muted">{isOffline ? "Offline" : "Live"}</Text></View></View>
      {isOffline ? <View style={{ backgroundColor: colors.warningSoft }} className="mt-3 flex-row items-center gap-2 rounded-2xl px-4 py-3"><MaterialIcons name="cloud-off" size={18} color={colors.warning} /><Text style={{ color: colors.warning }} className="flex-1 text-xs font-bold">Offline mode · showing last known bus positions</Text></View> : <View style={{ backgroundColor: colors.successSoft }} className="mt-3 flex-row items-center gap-2 rounded-2xl px-4 py-3"><MaterialIcons name="sensors" size={18} color={colors.success} /><Text style={{ color: colors.success }} className="flex-1 text-xs font-bold">Live arrivals updated just now</Text><Text style={{ color: colors.success }} className="text-[10px] font-black">{activeBuses.length} BUSES</Text></View>}
      <Card style={{ backgroundColor: colors.primary }} className="mt-5 overflow-hidden"><Text className="text-[11px] font-black uppercase tracking-[1.5px] text-white/75">Check your bus status</Text><Text className="mt-2 text-2xl font-black leading-8 text-white">Where is your bus?</Text><Text className="mt-1 text-sm text-white/80">Search by bus number, route, stop, or vehicle.</Text><View className="mt-4 flex-row items-center rounded-2xl bg-white px-3"><MaterialIcons name="search" size={21} color={colors.muted} /><TextInput value={statusQuery} onChangeText={setStatusQuery} onSubmitEditing={handleStatusSearch} placeholder="e.g. 101, BUS-101, Kottara" placeholderTextColor={colors.muted} returnKeyType="search" className="h-14 flex-1 pl-3 text-[14px] text-foreground" /><Pressable onPress={handleStatusSearch} className="rounded-xl px-2 py-2"><Text style={{ color: colors.primary }} className="font-black">CHECK</Text></Pressable></View><View className="mt-4 flex-row gap-2"><MiniAction icon="location-on" title="Nearby stops" onPress={() => router.push("/(tabs)/nearby")} /><MiniAction icon="schedule" title="Timetable" onPress={() => router.push("/timetable")} /><MiniAction icon="route" title="Routes" onPress={() => router.push("/(tabs)/routes")} /></View></Card>
      <View className="mt-6"><View className="mb-3 flex-row items-center justify-between"><View><Text className="text-xl font-black text-foreground">Plan a journey</Text><Text className="mt-1 text-xs text-muted">Find the fastest direct bus</Text></View><Pressable onPress={() => router.push("/plan")}><Text style={{ color: colors.primary }} className="text-xs font-black">OPEN PLANNER</Text></Pressable></View><Card><View className="gap-2"><PlaceField color={colors.primary} value={from} onChangeText={setFrom} placeholder="From" /><View className="ml-2 h-3 border-l border-dashed border-border" /><PlaceField color={colors.warning} value={to} onChangeText={setTo} placeholder="To" /></View><PrimaryButton title="Find buses" icon="arrow-forward" onPress={() => router.push(`/plan?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`)} style={{ marginTop: 14 }} /></Card></View>
      <View className="mt-6"><View className="mb-3 flex-row items-center justify-between"><View><Text className="text-xl font-black text-foreground">Live around you</Text><Text className="mt-1 text-xs text-muted">Tap a bus to see its full journey</Text></View><Pressable onPress={() => router.push("/(tabs)/track")}><Text style={{ color: colors.primary }} className="text-xs font-black">VIEW MAP</Text></Pressable></View><BusMap buses={activeBuses.slice(0, 5)} selectedBusId={activeBuses[0]?.id} onSelectBus={(id) => router.push(`/bus/${id}`)} /><View className="mt-3 gap-2">{activeBuses.slice(0, 3).map((bus) => <Pressable key={bus.id} onPress={() => router.push(`/bus/${bus.id}`)} className="flex-row items-center rounded-2xl bg-surface px-3 py-3"><View style={{ backgroundColor: colors.primarySoft }} className="mr-3 h-10 w-10 items-center justify-center rounded-xl"><MaterialIcons name="directions-bus" size={19} color={colors.primary} /></View><View className="flex-1"><View className="flex-row items-center gap-2"><Text className="font-black text-foreground">{bus.id}</Text><StatusPill label={bus.status === "DELAYED" ? "DELAYED" : "LIVE"} tone={bus.status === "DELAYED" ? "warning" : "success"} /></View><Text className="mt-1 text-xs text-muted">{bus.currentStop} → {bus.nextStop}</Text></View><View className="items-end"><Text style={{ color: colors.primary }} className="text-lg font-black">{bus.eta} min</Text><Text className="text-[10px] text-muted">to next stop</Text></View></Pressable>)}</View></View>
      <View style={{ backgroundColor: colors.surfaceAlt }} className="mt-6 rounded-2xl p-4"><View className="flex-row items-center gap-2"><MaterialIcons name="info-outline" size={18} color={colors.primary} /><Text className="font-black text-foreground">Service information</Text></View><Text className="mt-2 text-xs leading-5 text-muted">{demoLocation ? "You are viewing the Mangaluru demo network. Arrival times update automatically." : "Location services are enabled for nearby arrivals."} Check route details before you travel.</Text></View>
    </ScrollView>
  </ScreenContainer>;
}

function PlaceField({ color, value, onChangeText, placeholder }: { color: string; value: string; onChangeText: (value: string) => void; placeholder: string }) { const colors = useColors(); return <View style={{ borderColor: colors.border }} className="flex-row items-center rounded-xl border px-3"><View style={{ backgroundColor: color }} className="h-2.5 w-2.5 rounded-full" /><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.muted} className="h-12 flex-1 pl-3 text-sm text-foreground" /></View>; }
function MiniAction({ icon, title, onPress }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; onPress: () => void }) { return <Pressable onPress={onPress} className="flex-1 flex-row items-center gap-1.5 rounded-xl bg-white/15 px-2 py-2.5"><MaterialIcons name={icon} size={16} color="#FFFFFF" /><Text className="text-[10px] font-black text-white">{title}</Text></Pressable>; }
