import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import React, { useState } from "react";
import { Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { BusMap } from "@/components/bus-map";
import { Card, SectionTitle, StatusPill } from "@/components/transport-ui";
import { useColors } from "@/hooks/use-colors";
import { useAppState } from "@/lib/app-state";

export default function TrackScreen() {
  const colors = useColors();
  const { buses, isOffline } = useAppState();
  const [selected, setSelected] = useState(buses[0]?.id);
  const [query, setQuery] = useState("");
  const filtered = buses.filter((bus) => !query || `${bus.id} ${bus.vehicle} ${bus.currentStop}`.toLowerCase().includes(query.toLowerCase()));
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 28 }}><View className="pt-2"><Text className="text-3xl font-black text-foreground">Track live</Text><Text className="mt-1 text-sm text-muted">Watch buses move along their route in real time.</Text></View><View style={{ borderColor: colors.border }} className="mt-5 flex-row items-center rounded-2xl border bg-surface px-4"><MaterialIcons name="search" size={20} color={colors.muted} /><TextInput value={query} onChangeText={setQuery} placeholder="Bus or vehicle number" placeholderTextColor={colors.muted} className="h-14 flex-1 pl-3 text-sm text-foreground" /></View>{isOffline ? <View style={{ backgroundColor: colors.warningSoft }} className="mt-3 flex-row items-center gap-2 rounded-2xl px-4 py-3"><MaterialIcons name="cloud-off" size={17} color={colors.warning} /><Text style={{ color: colors.warning }} className="text-xs font-bold">Offline mode: last known positions only</Text></View> : null}<View className="mt-4"><BusMap buses={filtered} selectedBusId={selected} onSelectBus={(id) => { setSelected(id); router.push(`/bus/${id}`); }} /></View><View className="mt-6"><SectionTitle title="Active fleet" /><View className="gap-3">{filtered.map((bus) => <Pressable key={bus.id} onPress={() => { setSelected(bus.id); router.push(`/bus/${bus.id}`); }}><Card><View className="flex-row items-center"><View style={{ backgroundColor: colors.primarySoft }} className="mr-3 h-11 w-11 items-center justify-center rounded-xl"><MaterialIcons name="directions-bus" size={21} color={colors.primary} /></View><View className="flex-1"><View className="flex-row items-center gap-2"><Text className="font-black text-foreground">{bus.id}</Text><StatusPill label={bus.status === "DELAYED" ? "DELAYED" : bus.status === "STOPPED" ? "STOPPED" : "LIVE"} tone={bus.status === "DELAYED" ? "warning" : bus.status === "STOPPED" ? "muted" : "success"} /></View><Text className="mt-1 text-xs text-muted">{bus.currentStop} → {bus.nextStop}</Text></View><View className="items-end"><Text style={{ color: colors.primary }} className="text-xl font-black">{bus.eta} min</Text><Text className="text-[10px] text-muted">ETA · {bus.speed} km/h</Text></View></View><View className="mt-3 flex-row items-center gap-2 border-t border-border pt-3"><MaterialIcons name="update" size={14} color={colors.muted} /><Text className="text-xs text-muted">Updated just now · route {bus.routeId}</Text><Text className="ml-auto text-xs font-bold text-primary">View details</Text></View></Card></Pressable>)}{filtered.length === 0 ? <Text className="py-8 text-center text-sm text-muted">No buses match that search.</Text> : null}</View></View></ScrollView></ScreenContainer>;
}
